---
title: "Exercise 2.9 - Changing code on the fly"
workshops: openshift_v3_azure
workshop_weight: 10
layout: lab
---

:domain_name: redhatgov.io
:icons: font
:imagesdir: /workshops/openshift_v3_azure/images


= Exercise 2.9 - Changing code on the fly

== Section 1: Changing code on the fly

In this lab, we will learn how to make changes to the code on the local machine and immediately sync it with the code running in a pod.

*Note:* This model of programming is useful for interpreted languages.

*Prerequisite:* This lab assumes that you have git installed on your box

=== Step 1: Create a new project

Create a new project on the OpenShift cluster with name `synccode-{{< urifqdn_user "labuser""" >}}`

=== Step 2: Clone the git repository locally

Clone the following git repository to your workstation. https://github.com/VeerMuchandi/nodejs-hello using the command

[source,bash]
----
git clone https://github.com/VeerMuchandi/nodejs-hello
----

This is a very simple nodejs application. Feel free to understand the code.

=== Step 3: Create the application

Change to the `nodejs-hello` folder.

[source,bash]
----
cd nodejs-hello
----

Now let us create an application using this code.

[source,bash]
----
oc new-app . --image-stream=nodejs:4
----

Create a route

[source,bash]
----
oc expose service nodejs-hello
----

Wait for the build to complete and test the application

[source,bash]
----
oc get route
----

[source,bash]
----
curl nodejs-hello-rsync-{{< urifqdn_user "labuser""" >}}.104.209.170.217.nip.io
----

=== Step 4: Make code changes and sync with rsync

Let us now make a small change to the application on your workstation.

Edit `server.js file` using your favorite text editor (I use vi). The code snippet below displays the welcome message

[source,bash]
----
app.get('/', function (req, res) {
  res.send('Welcome to OpenShift!! My HostName is: ' + os.hostname() + '\n');
});
----

Let us make a small change to insert a \n character after the welcome message so that the hostname is displayed on a different line. The edited code should look like this.

[source,bash]
----
app.get('/', function (req, res) {
  res.send('Welcome to OpenShift!! \n My HostName is: ' + os.hostname() + '\n');
});
----

Run `oc get pods` to get your application pod name as shown below:

Use `oc rsync` to sync the code from the local workstation to the pod as shown below

[source,bash]
----
oc rsync . nodejs-hello-1-8qigc:/opt/app-root/src --no-perms=true --exclude=.git
----

The command above will copy the code from the local machine to the pod. Note that

- `/opt/app-root/src` is the default home location on the pod
- `--exclude=.git` will omit the hidden git folder

Now test the application again. This time it should show the output in two lines as below:

[source,bash]
----
curl nodejs-hello-rsync-veer.104.209.170.217.nip.io
----

Note that pod did not restart, we did not have to check into git repo and rebuild the image. The changes moved from your workstation directly to the pod.

Developers can use this mechanism to quickly test the changes on the fly. When ready they can commit the changes to the source control repository.

You can repeat a few more changes and enjoy the rsync!!!

{{< importPartial "footer/footer_openshift_v3_azure.html" >}}
