---
title: "Exercise 1.8 - Using SSL in your application"
workshops: openshift_v3_azure
workshop_weight: 10
layout: lab
---

:domain_name: redhatgov.io
:icons: font
:imagesdir: /workshops/openshift_v3_azure/images


= Exercise 1.8 - Using SSL in your application

== Section 1: Using SSL in your application

In this exercise you will set up your application to encrypt traffic with the OpenShift Wildcard certificate.

=== Step 1: Switch to an existing project

For this exercise, we will use an application that we created before. We will be using the myjbossapp-{{< urifqdn_user "labuser""" >}} that you created in the previous labs. Make sure you are switched to that project by using the oc project command. Remember to substitute UserName.

[source,bash]
----
oc project myjbossapp-{{< urifqdn_user "labuser""" >}}
----

=== Step 2: View the routing config

To view the routing config you will need to use the `oc get route` command

[source,bash]
----
oc get route/ks -o yaml
----

Note here that the *host*: is set to the FQDN that your application is running on.

Currently the routing component of OpenShift 3 supports ports *80* and *443*. When you first create your route, the mapping of *80* to your pod is done automatically. There are a few things that need to be done in order to get the *443* mapping to work.


=== Step 3: TLS Edge Termination

OpenShift has a *wildcard SSL* certificate that it can use for any application. We can use this SSL certificate to serve SSL from our application without having to generate a cert of our own (which is sometimes called SSL-offloading).

Edit your routing configuration:

[source,bash]
----
oc edit route/ks
----

You are going to add tls: `termination: edge` right below the `host:` section. It should look something like this.

[source,bash]
----
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2015-12-22T03:56:30Z
  labels:
    app: ks
  name: ks
  namespace: myjbossapp-{{< urifqdn_user "labuser""" >}}
  resourceVersion: "2903142"
  selfLink: /oapi/v1/namespaces/myjbossapp-{{< urifqdn_user "labuser""" >}}/routes/ks
  uid: fba5d1e6-a85f-11e5-be21-fa163ec58dad
spec:
  host: ks-myjbossapp-{{< urifqdn_user "labuser""" >}}.104.209.170.217.nip.io
  tls:
    termination: edge
  port:
    targetPort: "8080"
  to:
    kind: Service
    name: ks
status: {}
----

====
[NOTE]
The spacing in a yaml file is crucial. Please review the spacing before saving your configuration.
====

=== Step 4: Verify

Verify by visiting your page by using the *https://* URI

[source,bash]
----
oc get route
----

====
[NOTE]
The system may ask you to accept access to an unsecure host
====

Congratulations!! In this exercise you have learned about service SSL from your application

{{< importPartial "footer/footer_openshift_v3_azure.html" >}}
